### ISSUE TITLE
'queue-version' value not converted to integer in rabbitmq_policy.rb

### ISSUE THREAD

**Issue by alphamonkey79** [voxpupuli/puppet-rabbitmq#1017]
## Affected Puppet, Ruby, OS and module versions/distributions

https://github.com/voxpupuli/puppet-rabbitmq/blob/master/lib/puppet/type/rabbitmq_policy.rb#L5-L15

- Puppet:
- Ruby:
- Distribution:
- Module version:

## How to reproduce (e.g Puppet code you use)
```
  # 'ha-all' policy settings.
  rabbitmq_policy { "ha-all@${name}":
    ensure     => $ensure,
    pattern    => '.*',
    priority   => 10,
    applyto    => 'all',
    definition => {
      'ha-mode'                => $real_policy_ha_mode,
      'ha-params'              => $real_policy_ha_params,
      'ha-sync-mode'           => $real_policy_ha_sync_mode,
      'ha-sync-batch-size'     => $real_policy_ha_sync_batch_size,
      'queue-master-locator'   => $real_policy_queue_master_locator,
      'ha-promote-on-failure'  => $real_policy_ha_promote_on_failure,
      'ha-promote-on-shutdown' => $real_policy_ha_promote_on_shutdown,
      'max-length'             => $policy_max_length,
      'max-length-bytes'       => $policy_max_length_bytes,
      'queue-version'         => 2,
    },
```

## What are you seeing
ERROR: not a string

## What behaviour did you expect instead
change classic queue version from 1 to 2

**Comment by wyardley** [comment]
[edited your description to put the Puppet code in triple-backticks]

Is it `queue-type` or `queue-version`? And are we trying to convert string to int or int to string? I believe in this case, the issue is that we need to convert it from string to int rather than vice-versa?

Since we already added that list, should be a relatively easy fix by adding to the list you linked to - would you be able to make a PR with that fix?

It should also have a test that the value is converted, similar to the one added here:
https://github.com/voxpupuli/puppet-rabbitmq/pull/991/files

**Comment by wyardley** [comment]
(I know in  the puppet code it looks like it's already an integer, but I think this may be the Puppet DSL magic ✨?)

**Comment by wyardley** [comment]
@alphamonkey79 I went ahead and implemented it - can you test the new version and confirm that it works now?

**Comment by alphamonkey79** [comment]
Hello @wyardley 

Thank you for the assistance!
We are updating from module v12.1.0 to v13.7.0 as soon as possible and will confirm after thorough testing.

Tim
