### ISSUE TITLE
Idempotency problems with rabbitmq 3.6.5 and puppet 4.8.2

### ISSUE THREAD

**Issue by mwhahaha** [voxpupuli/puppet-rabbitmq#618]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.8.2
- Ruby: ruby-2.0.0.648-29.el7.x86_64
- Distribution: centos 
- Module version: 70ac6c59180a307786db28218d11348acc6d7a42
- Rabbitmq 3.6.5

## How to reproduce (e.g Puppet code you use)
https://github.com/openstack/puppet-openstack-integration/blob/master/manifests/rabbitmq.pp

## What are you seeing
Idempotency problem with the rabbit config
```
2017-09-07 17:11:16 +0000 /Stage[main]/Rabbitmq::Config/File[rabbitmq.config]/content (notice): 
--- /etc/rabbitmq/rabbitmq.config	2017-09-07 16:47:01.384000000 +0000
+++ /tmp/puppet-file20170907-7672-1kuhj4r	2017-09-07 17:11:16.605000000 +0000
@@ -3,9 +3,6 @@
 [
   {rabbit, [
     {tcp_listen_options, [
-         binary,
-         {packet,        raw},
-         {reuseaddr,     true},
          {backlog,       128},
          {nodelay,       true},
          {linger,        {true, 0}},
2017-09-07 17:11:16 +0000 Puppet (info): Computing checksum on file /etc/rabbitmq/rabbitmq.config
2017-09-07 17:11:16 +0000 /Stage[main]/Rabbitmq::Config/File[rabbitmq.config] (info): Filebucketed /etc/rabbitmq/rabbitmq.config to puppet with sum 21f23f84e979e437300cf0f14cecc889
2017-09-07 17:11:16 +0000 /Stage[main]/Rabbitmq::Config/File[rabbitmq.config]/content (notice): content changed '{md5}21f23f84e979e437300cf0f14cecc889' to '{md5}0ef507de9e71257dcc93b8974445296b'
2017-09-07 17:11:16 +0000 /Stage[main]/Rabbitmq::Config/File[rabbitmq.config] (info): Scheduling refresh of Class[Rabbitmq::Service]
2017-09-07 17:11:16 +0000 Class[Rabbitmq::Config] (info): Scheduling refresh of Class[Rabbitmq::Service]
2017-09-07 17:11:17 +0000 Class[Rabbitmq::Service] (info): Scheduling refresh of Service[rabbitmq-server]
2017-09-07 17:11:34 +0000 /Stage[main]/Rabbitmq::Service/Service[rabbitmq-server] (notice): Triggered 'refresh' from 1 events
```

## What behaviour did you expect instead
The code is idempotent

## Output log
http://paste.openstack.org/raw/620656/

## Any additional information you'd like to impart
Might be related to this change, https://github.com/voxpupuli/puppet-rabbitmq/commit/1c42f4205e566c7a766e7bdeeff0867592cbbdc2 as the previous logic did not suffer from this problem

**Comment by wyardley** [comment]
Yes, I think it is related to that change, I was concerned that could happen at the time. I'm not sure what a good fix is for it, since we can no longer reasonably set `version`, and we can't get `rabbitmq_version` (with the way the fact is implemented currently, at least) until it's installed. We could improve things a little by making the default enabled for those options. Open to suggestions

@ekohl @alexjfisher

**Comment by wyardley** [comment]
ps - I think it was introduced here (and I did comment about it there) https://github.com/voxpupuli/puppet-rabbitmq/pull/493/files#diff-0ac866172efd29d0ddc2aa75ae6f182dR120
with the original code in #464 by @mpolenchuk

**Comment by mwhahaha** [comment]
Yea it's possible the earlier one did it, we recently bumped from 5.6.0 to capture some functionality to support tls.  I'm not an expert on the rabbitmq config and it seemed to not break anything having it defined in the config on the initial rabbitmq startup.  What's the impact of having those 3 listen options vs not?   Do we actually need this logic or could we allow operators to opt into it?

**Comment by wyardley** [comment]
#464 explains it better (and links to https://github.com/rabbitmq/rabbitmq-server/issues/453), but I think those options shouldn't be there in versions >3.6

I'm not sure if they're harmful if present.
While the itempotency issue is a problem, I think it will only happen on the second run, or when RMQ version changes above / below the comparison, right (i.e., once the rabbitmq_version fact is properly computed, the config shouldn't change).

**Comment by mwhahaha** [comment]
It does restart only on the second run, but in our case that's a rabbitmq restart which is not ok.  Rather than relying on the fact it would be beneficial to have a flag to disable this for the instances where the operators knows this ahead of time and does not want this type of functionality.

**Comment by wyardley** [comment]
We could see if just reverting the conditional introduced in #464 would cause errors (i.e., if those directives are messy, but harmless), or I guess introduce a parameter to suppress the lines, though I don't love that option.

**Comment by ekohl** [comment]
My knowledge of rabbitmq is limited so I can mostly advise on the puppet side of the module but some options I see:
1. Expand the fact to query the package manager for available versions. That does mean all repositories should be present before the actual installation and it would be an approximation. With possible incorrect results you could have a restart.
2. Assume ranch is present if the fact is absent. If rabbitmq fails to start you wouldn't have idempotency but you never start the server with an incorrect config. The second run will correct it and start the server since the package should then be installed.
3. Similar to 2 but make some distro-based hardcoded defaults about the version.

**Comment by wyardley** [comment]
@ekohl thanks
I did briefly consider # 1 - but I think there are some potential issues there. We'd need to make sure it happens after installation but before configuration in the same run (not sure if you can do that with facts), and you'd also have to account for the different version formats and different packaging systems.

# 2 should be the same as the current behavior, I think.
# 3 is not really possible, I think, because we support both configuring from OS vendor (or EPEL) and from RabbitMQ's repos, and with setting `$package_ensure` to different versions, we can't really assume that RabbitMQ will be a particular version even on a specific OS.

So the most conservative thing would probably be to lose the change, assuming it's just harmless and messy vs. a breaking issue where the service won't start.

**Comment by mwhahaha** [comment]
So there are problems with these which is why I asked to allow the operator to specify.

For 1. If you do repo setup in your puppet catalog, this won't get the actual versions.  For 3. if you assume version but operator uses own repo it'll never be right.   

To be honest this is my least favorite thing that happens with puppet modules when you have to manage different config formats depending on the version because this is exactly where it falls down.

I would go for 2 and document that this version of the module must have min version of rabbitmq X.Y.Z or say if you don't have X.Y.Z you must enable $setting.

**Comment by ekohl** [comment]
> So there are problems with these which is why I asked to allow the operator to specify.

If you move the value based on the fact to ```params.pp``` and expose it as a parameter then that's fine. Sane(ish)  defaults with the power to override is usually the way to go, especially when your default is know to be imperfect.

> For 1. If you do repo setup in your puppet catalog, this won't get the actual versions. For 3. if you assume version but operator uses own repo it'll never be right.

I see the downsides as well, just wanted to put all the options out there.

> To be honest this is my least favorite thing that happens with puppet modules when you have to manage different config formats depending on the version because this is exactly where it falls down.

Absolutely. Having static facts during the run is great in many ways, but here it does break down.

> I would go for 2 and document that this version of the module must have min version of rabbitmq X.Y.Z or say if you don't have X.Y.Z you must enable $setting.

I was considering a hybrid where the default value in params.pp is based on the fact with a fallback that's compatible with X.Y.Z but maybe your deterministic approach is better. I've never been a fan of version_x facts because, as you say, the model in puppet doesn't support it. Let's not pretend it does.

**Comment by mwhahaha** [comment]
No I'm talking about a version_x fact.  In fact I was describing your hybrid approach by allowing the operator to pass in $rabbitmq::params::ranch = true (or false) and an operator can override or whatever and they get the config they did. I'm a huge fan of less automagic and more sane defaults and flexibility to enable/disable this type of functionality.

Right now as a consumer, I have no way of specifying that you don't do this config automagic.  So for us until we either revert to an older version (and lose tls support) or figure out a solution here we're blocked. Just a s aside note even if we do figure out a solution I know the next problem for us is the puppet-staging to puppet-archive switch but that's our problem.

**Comment by ekohl** [comment]
The benefit of the fact-based default is that it's the status quo with an override so it's a patch or minor version so 👍 on avoiding a major version bump.

**Comment by wyardley** [comment]
Yeah, I think I'll take a gander at implementing it as a parameter (defaulting to `true` in params). I think generally we don't pass values directly to params, but could set it up using the same pattern as existing parameters.

One approach that could also be a slight improvement would be to invert the current behavior so that the default is to drop those parameters. Then, the idempotency issue would still exist, but it would affect only users of older RabbitMQ versions.

**Comment by wyardley** [comment]
I've added tests to the possible fix, will see what folks think about the naming of the parameter.

**Comment by wyardley** [comment]
#621 has been approved and merged; I'd like a better fix for this, but I think the current behavior should support most new installations, while still allowing older installations to work w/ a config parameter.
