### ISSUE TITLE
Missing at least one release for Puppet 3.8.x

### ISSUE THREAD

**Issue by GhostLyrics** [voxpupuli/puppet-rabbitmq#627]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 3.8.x
- Ruby:
- Distribution: Ubuntu Trusty
- Module version: *well…*

Considering that the previous page at the forge: https://forge.puppet.com/puppetlabs/rabbitmq now states that module is deprecated and the first release here is 6.0.0, would you consider publishing at least the very last module with Puppet 3 support again, at the forge for this module, please?

Otherwise when downloading via r10k, you get the deprecation warning, are redirected here and find no compatible release here. I find this to be frustrating.

Thank you.

**Comment by wyardley** [comment]
I'll ask, but might be tough at this point. I know for some modules, Vox Pupuli has kept a Puppet 3 branch around, but there is not one for this module. I'm sympathetic, since we were on Puppet 3 til very recently ourselves, but Vox has been dropping support for 3.x since it was EOLed, so you may have to live with the older version.

I think r10k supports using a git repo as a source, so maybe you could pin to a commit around 9202dd5f2992678a31e8e60247bd638ca79b333f and do it this way? Not sure if it's still possible to install 5.6 from forge, but that would probably be the other supported option.

**Comment by wyardley** [comment]
If we can get 5.6.0 under puppet/rabbitmq, would that solve the issue for you?

**Comment by GhostLyrics** [comment]
Yes, it would. I think that's the most elegant solution.

**Comment by wyardley** [comment]
@hunner cut 5.6.1, and we'll try to get that uploaded to the forge manually.

**Comment by wyardley** [comment]
https://forge.puppet.com/puppet/rabbitmq/5.6.1
Sorry that took so long to actually get up.

**Comment by GhostLyrics** [comment]
Thank you very much.
