### ISSUE TITLE
rabbitmqadmin install has no way of continuing to use staging in environments using an incompatible archive module

### ISSUE THREAD

**Issue by heliocentric** [voxpupuli/puppet-rabbitmq#659]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.10.0
- Ruby: puppet-agents
- Distribution: rhel7
- Module version: v8.0.0

## How to reproduce (e.g Puppet code you use)

Use the puppetlabs/archive module in your environment. 

## What are you seeing

Unable to install using the vendor archive module due to parameter incompatibilities.

## What behaviour did you expect instead

The ability to default back to the old behavior of using staging.

## Any additional information you'd like to impart

This module used to use staging, which has an older and more established api. Because there are two archive modules with different lineages, some modules require one while other modules require others. When rabbitmqadmin install was converted over to using archive instead of staging, there was no way to handle environments that used the incompatible api due to existing modules.

**Comment by wyardley** [comment]
As best I understand, staging has been deprecated for quite some time.
I have dealt with the competing archive module dependency in the past as well, so I know it's annoying, but I don't think there's any current plan to have this module fall back to staging module or support both.
It's not a great fix, esp. because of the caching issue, but we used to work around this via PUppet environments.
