### ISSUE TITLE
Q: How do I use Hiera yaml syntax for RabbitMQ types

### ISSUE THREAD

**Issue by mkelderm** [voxpupuli/puppet-rabbitmq#673]
How do I use Hiera yaml syntax to access the RabbitMQ module, especially users/persmissions/ policies? IMHO I am using the syntaxis: (but they do not apply as I am running puppet).
```
rabbitmq_user:
   "rmqadmin":
     admin:    true
     password: 'rmqadmin'
     tags:     [ 'rmqadmin' ]
   "monitor":
     admin:    false
     password: 'monitor'
     tags:     [ 'monitoring' ]

rabbitmq_user_permissions:
  "rmqadmin@/":
    configure_permission: '.*'
    write_permission:     '.*'  
    read_permission:      '.*'
  "monitor@/":            
    configure_permission: ''
    write_permission:     '' 
    read_permission:      '.*'

rabbitmq_policy:
  "HA-Queue-Definitions@/":
    pattern:    '^(?!amq.).*'
    priority:   0
    applyto:    'all'
    definition: 
      - ha-mode:  'all'

```

**Comment by wyardley** [comment]
I don't think the module has a passthrough, so you can't just do `rabbitmq::rabbitmq_policies` (for example), and if you defined >1 `rabbitmq::rabbitmq_policy` in hiera, I think it might not work because of how the data would have to be structured. What we did to define these in hiera was something along the lines of (for each resource type) in a site wrapper we used for this role:

```puppet
  $user_defaults = {
    admin    => false,
  }
  $queue_defaults = {
    user        => $admin_user,
    password    => $admin_pass,
    [....]
  }
 [etc]
  create_resources(rabbitmq_user, $users, $user_defaults)
  create_resources(rabbitmq_queue, $queues, $queue_defaults)
```
and then in hiera:
```yaml
role::rabbitmq::users:
  foo:
    password: hunter2
    tags:
      - monitoring
and so on
```

In theory, a PR could be created to add passthrough params, similar to how nginx module has them, not sure whether all the extra code and params needed to support this would  be worthwhile, though.

**Comment by wyardley** [comment]
@mkelderm: let me know if that answers your question.
