### ISSUE TITLE
Error 765 after latest update

### ISSUE THREAD

**Issue by wortmanb** [voxpupuli/puppet-rabbitmq#741]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.0.2
- Ruby: 2.0.0p648
- Distribution: CentOS 7.5.1804
- Module version: 5.5.0

## How to reproduce (e.g Puppet code you use)

puppet agent -t --tags rabbitmq

## What are you seeing

No matter what tags I try to restrict the puppet agent run to, it always errors with this, which I believe relates to rabbitmq because I only see this behavior on systems that implement it:

Error: Failed to apply catalog: 765: unexpected token at 'arguments'

## What behaviour did you expect instead

Successful completion...

## Any additional information you'd like to impart

Our configuration worked just great until we upgraded to the above versions but there appear to have been a number of changes to RMQ. We're also on RMQ 3.7.9. I'm looking at the various places where json processing is done (765 appears to be a JSON error). This isn't fact-related, so I think it's somewhere under lib/puppet/provider/... I'll keep looking but am hopeful I can get some more knowledgeable folk to point me in the right direction.

**Comment by wyardley** [comment]
Maybe run `puppet-agent` with `--debug` - that should at least provide a better hint of what's failing where.
Are you really using module version 5.5.0? I would definitely update to 8.4.0 if you haven't already.

**Comment by wortmanb** [comment]
Wait, I thought I had upgraded to the latest & greatest... Standby.

**Comment by wortmanb** [comment]
No, it is 8.4.0. I looked at HISTORY.md before realizing that it wasn't actively in use any more.

**Comment by wyardley** [comment]
The 5.x releases are under the puppetlabs namespace, before Vox took over the module: https://forge.puppet.com/puppetlabs/rabbitmq vs https://forge.puppet.com/puppet/rabbitmq (yes, it's confusing that Vox is "puppet"). There should be a deprecation notice on the forge page for the former.

**Comment by wyardley** [comment]
In addition to the debug output, maybe include the relevant bits of your config. Also, have a read of #740 if you haven't already, though this seems like a slightly different issue. Probably someone should rework the providers to use json output where feasible, and / or switch to using the HTTP API.

There hasn't been much work on this lately, and I don't have the time / inclination to do much, but if you can post the above, may be able to give you some help in terms of where to look, at least.

I will note that the module doesn't specifically say that it supports / has been tested against 3.7.x; 3.6.x should work.
https://github.com/voxpupuli/puppet-rabbitmq#module-description

You also can check out #voxpupuli on IRC / Puppet Community Slack.

**Comment by wortmanb** [comment]
Here's what I think is the relvant section (my system's airgapped, so any apparent typos here are just transcription errors):

```
Debug: Executing: '/usr/sbin/rabbitmqctl -q list_exchanges -p name name type internal durable auto_delete arguments'
Debug: Command succeeded
Debug: Executing: '/usr/sbin/rabbitmqctl -q list_exchanges -p syslog name type internal durable auto-delete arguments'
Debug: Command succeeded
Debug: Storing state
Debug: Pruned old state cache entries in 0.00 seconds
Debug: Stored state in 0.05 seconds
Error: Failed to apply catalog: 765: unexpected token at 'arguments'

```

When I try this by hand:

```
# rabbitmqctl -q list_exchanges -p syslog name type internal durable auto_delete arguments
name    type      internal      durable auto_delete    arguments
amq.rabbitmq.trace    topic    true    true    false    []
.
.
.
```
I'm betting it's the header row that's giving us problems. When I add "--no-table-headers" after the "-q", this seems to work just fine on the command line. I'll patch the code here and see if I can get past (another of these) annoying header row changes.

**Comment by wortmanb** [comment]
That cleared it up. Thanks for the pointers.

**Comment by wyardley** [comment]
Thanks! If you're able / willing to go through some back and forth to make sure it's backwards compatible and tested / tests clean, please submit a PR for this. Per the comment in other PR, the best (though not easiest) solution may be to use the json output format.

**Comment by wortmanb** [comment]
I just forked the project and will gladly take a pass at making these changes good enough for a PR. Thanks for your help!

**Comment by wortmanb** [comment]
Is there an easy way to test my changes against earlier versions without having to install multiple older versions myself?

**Comment by wyardley** [comment]
> Is there an easy way to test my changes against earlier versions without having to install multiple older versions myself?

It depends how you make your changes. If you're switching to JSON output, you'll have to update all the test cases, whereas if you're adjusting the regex, you could make new unit tests with the new expected output, and also keep the old ones. I prefer the former, but for that, all the expected output will have to be changed, so we need to be a little bit more careful. You'd probably want to install the old versions _somewhere_, just to make sure that the expected output format is the same, and that the supported versions do support that output format for those commands. I'd be Ok with making this a breaking change if it turns out some super old versions of RabbitMQ don't support that.

The integration test will run with an older version by default (IIRC 3.3.x maybe? you could look in the travis run to see what gets installed), so running those will give us some idea that it's backwards compatible.

Does that make sense?

What I'll typically do is set `BEAKER_destroy=no`, and run, say, `bundle exec rake beaker:centos-7-x64`, and once the test is done, you can run `rake beaker:ssh:centos-7-x64` to ssh into the instance, and play around with installing different versions of rabbitmq or testing other changes live in the integration test environment. You can also use the manifests created in `/tmp` as a starting point for creating some manifests to test different behavior.

**Comment by wortmanb** [comment]
Makes perfect sense. Available time (and extra computing resources) is my enemy right now, but I will try to do what I can if no one else gets to it first.

**Comment by wyardley** [comment]
It does look like you can reference facts within providers. Whether it's safe to just key this on `rabbitmq_version` fact, I'm not totally sure.

See some other notes that I put in https://github.com/voxpupuli/puppet-rabbitmq/issues/740#issuecomment-445433853 and the comments there from Michael.

**Comment by wyardley** [comment]
Closing via #759
