### ISSUE TITLE
Does not find rabbitmqadmin under ubuntu

### ISSUE THREAD

**Issue by hadmut** [voxpupuli/puppet-rabbitmq#812]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.4.0
- Ruby: 2.5.1
- Distribution: Ubuntu 18.04
- Module version: 9.1.0

## How to reproduce (e.g Puppet code you use)
just follow your examples

## What are you seeing

Error: Command rabbitmqadmin is missing
Error: /Stage[main]/H_server::Message::Rabbitmq/Rabbitmq_exchange[blabla@test]/ensure: change from 'absent' to 'present' failed: Command rabbitmqadmin is missing

when installing rabbitmq-server package under ubuntu (even through your rabbitmq class), the rabbitmqadmin command goes to /usr/bin, but this module expects it to be under /usr/local/bin, thus does not find it and aborts.

**Comment by sjjf** [comment]
This is due to the Ubuntu packages installing rabbitmqadmin themselves, where the upstream packages don't (see https://github.com/rabbitmq/rabbitmq-server/issues/605 for some discussion, as well as a few other issues).

I think a fix/workaround would be to try both locations and use whichever it finds?

**Comment by sjjf** [comment]
Actually, scratch my comment - with the current version of the module puppet will create /usr/local/bin/rabbitmqadmin unless you do something to stop it, so this shouldn't be a problem. It's not /necessary/ to do with the Ubuntu packaged rabbitmq-server, but it doesn't break things.
